---
title: "Welcome to the Crowd-sourced COVID-19 Involentary Government Restrictions (CCIGR) Dataset"
output: html_notebook
---

----------->[Please Submit a Report of a Government Restriction](https://forms.gle/ESytGHMzUTvNf6RJA){target="_blank"}  <------------

# Introduction

This is a crowdsourced data collection effort to record new mandatory government restrictions intended to slow the spread of COVID-19. 

We don't know the answers to two important questions:

1) How government interventions changes the rate of growth in COVID19 spread within a community

2) What determines when governments will implement some interventions rather than others

We WANT reports of restrictions that are

* By a government

* Mandatory (legally required)

* New (a change to the previous rules)

For example:

* On March 12th, Ohio banned gatherings of more than 100 people.

* On March 15th, Saudi Arabia banned flights to and from hotspot countries.

* On March 10, New Rochelle, NY closed schools and businesses other than grocery stores and delis.

We DO NOT want:

* VOLUNTARY restrictions (CDC recommending canceling gatherings of more than 50 people)

* PRIVATE restrictions (Google requested its employees transition to working remotely)

* CURRENT policies (Don't report that China currently has a ban on flights now, only report if China made the CHANGE on the date you give)

Two good sources of announcements are:

* [Google News](https://news.google.com/search?q=covid&hl=en-US)

* [Reddit](https://www.reddit.com/r/Coronavirus/)


Historical reports are welcome! (back to December 1, 2019)

Duplicate reports are fine, don't worry if it has already been submitted.

No personal information is requested, and the results will be made public for academic research.

Survey administered by Rex W. Douglass (PhD) (@RexDouglass), who will post results and further details as the project evolves at his twitter handle @RexDouglass . 

Follow the [twitter discussion](https://twitter.com/RexDouglass/status/1239781164392435712){target="_blank"}


----------->[Please Submit a Report of a Government Restriction](https://forms.gle/ESytGHMzUTvNf6RJA){target="_blank"}  <------------


<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, echo=F, cache=F, include = FALSE}
library(tidyverse)
library(googlesheets4)
library(knitr)
library(here)
path <- paste0(here::here(),"/data_temp/for_viewing_wide.Rds")
for_viewing_wide <- readRDS(path)
finf <- file.info(path, extra_cols = FALSE)

```

# The Data

Here are the data collected thus far (intended to update once an hour):
```{r, echo=F, cache=F}
print(paste("Last updated ", finf$mtime))
```

```{r, echo=F, cache=F}
library(DT)
datatable(for_viewing_wide, rownames = FALSE,
          options = list(
            pageLength = 100,
            columnDefs = list(list(className = 'dt-center', targets = "_all")
                              )
            )
)
```

----------->[Please Submit a Report of a Government Restriction](https://forms.gle/ESytGHMzUTvNf6RJA){target="_blank"}  <------------
