---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---


```{r}

library(lubridate)
library(tidyverse)
#library(R0)  # consider moving all library commands to top -- this one was in a loop below
#Until the U.S. states one goes live have to pull it from here
#Codebook
#https://github.com/JieYingWu/COVID-19_US_County-level_Summaries/blob/master/data/list_of_columns.md
counties <- read_csv(url("https://raw.githubusercontent.com/JieYingWu/COVID-19_US_County-level_Summaries/master/data/counties.csv")) #using the archived copy from today because they haven't posted the 
counties_t <- t(counties)

#The data contain the u.s. and the states too
#FIPS the first two digits are the state
#All 0 is the U.S.
#
#https://covidtracking.com/api
covidtracking <- read_csv(url("https://covidtracking.com/api/states/daily.csv")) #
dim(covidtracking) #1653   25
covidtracking_t <- t(covidtracking)


#https://github.com/nytimes/covid-19-data
nytimes <- read_csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")) #

```

```{r}

nytimes_long <- nytimes %>%
                mutate(date_asdate = ymd(date)) %>% 
                rename(confirmed=cases) %>%
                mutate(place=paste0(state,"_",county,"_",fips)) %>%
          group_by(place) %>%
            mutate(confirmed_cummax=cummax(confirmed)) %>%
            mutate(days_since_1_confirmed=cumsum(confirmed_cummax>=1)) %>%
            mutate(days_since_10_confirmed=cumsum(confirmed_cummax>=10)) %>%
            mutate(days_since_15_confirmed=cumsum(confirmed_cummax>=15)) %>%
            mutate(days_since_20_confirmed=cumsum(confirmed_cummax>=20)) %>%
  
            mutate(days_since_50_confirmed=cumsum(confirmed_cummax>=50)) %>%
            mutate(days_since_100_confirmed=cumsum(confirmed_cummax>=100)) %>%
            mutate(days_since_500_confirmed=cumsum(confirmed_cummax>=500)) %>%

            mutate(deaths_cummax=cummax(deaths)) %>%        
            mutate(days_since_1_deaths=cumsum(deaths_cummax>=1)) %>%
            mutate(days_since_10_deaths=cumsum(deaths_cummax>=10)) %>%
            mutate(days_since_50_deaths=cumsum(deaths_cummax>=50)) %>%
            mutate(days_since_100_deaths=cumsum(deaths_cummax>=100)) %>%
            mutate(days_since_500_deaths=cumsum(deaths_cummax>=500)) %>%

            mutate(confirmed_fd=confirmed-lag(confirmed)) %>%
            mutate(deaths_fd=deaths-lag(deaths)) %>%
          ungroup() %>%
          arrange(fips, date_asdate) %>%

          #filter(days_since_1_confirmed>0) %>%
          group_by(place) %>%
            mutate(confirmed_max=max(confirmed)) %>%
          ungroup() %>%

          mutate(deaths=ifelse(deaths==0, NA,deaths)) %>%
          mutate(confirmed=ifelse(confirmed==0, NA,confirmed))

places <- nytimes_long %>% dplyr::select(state, county, fips, place) %>% distinct()


temp <- nytimes_long %>% dplyr::select(fips, confirmed_max) %>% distinct()
table(temp$confirmed_max) #936 have 10 or more cases , 1412 don't

```


```{r}

#has new york city as a single entitiy but not the constituent counties which is frustrating

library(strucchange) ; #install.packages('strucchange')
temp <- nytimes_long %>% arrange(date_asdate) %>% filter(county %in% "Bexar") %>% 
        mutate(confirmed_log=log(confirmed+1)) %>%
        mutate(date_rank= rank(date_asdate))  
bp <- breakpoints(confirmed_log ~ 1, data=temp)
bp <- breakpoints(confirmed_log ~ 1 + date_rank, data=temp)
temp %>% ggplot() + geom_point(aes(x=rank(date_asdate), y=confirmed_log)) + geom_vline(xintercept=bp$breakpoints)
coef(bp)


temp <- nytimes_long %>% arrange(date_asdate) %>% filter(county %in% "New York City") %>% 
        mutate(confirmed_log=log(confirmed+1)) %>%
        mutate(t= rank(date_asdate))  
bp <- breakpoints(confirmed_log ~ 1, data=temp)
bp <- breakpoints(confirmed_log ~ 1 + t, data=temp)

tmin <- min(temp$t)
tmax <- max(temp$t)
c(tmin, bp$breakpoints, tmax)


cdf <- data.frame(
                  t= c(1,bp$breakpoints), 
                  t_slope= coef(bp)[,2]
                  )

temp <- temp %>% 
        mutate(y_hat = fitted.values(bp)) %>%
        left_join(cdf) %>% 
        fill(t_slope) %>%
        mutate(t_slope_percent_change = round((exp(t_slope)-1)*100,2))

temp %>% ggplot() +
         geom_point(aes(x=rank(date_asdate), y=confirmed_log)) + 
         geom_line(aes(x=rank(date_asdate), y=y_hat)) + 
         geom_vline(xintercept=bp$breakpoints)
```

```{r}

temp_list <- list()
for(q in places$place){
  print(q)
  temp <- NULL
  temp <- nytimes_long %>% 
          arrange(date_asdate) %>% 
          filter(place %in% q) %>% 
          mutate(confirmed_log=log(confirmed+1)) %>%
          mutate(t= rank(date_asdate))  
  if( nrow(temp)==0 ) {print("error"); break}

  #bp <- breakpoints(confirmed_log ~ 1, data=temp)
  bp <- NULL
  lm1 <- NULL
  y_hat <- NA
  cdf <- NULL
  try({
        #if it fails fall back to just a lm
    lm1 <- lm(confirmed_log ~ 1 + t, data=temp)

    cdf <- data.frame(
                      t= 1, 
                      t_slope= coef(lm1)[2],
                      t_slope_break=0
                      )
    y_hat=fitted.values(lm1)
  })
  
  try({
    bp <- breakpoints(confirmed_log ~ 1 + t, data=temp)
    
    cdf <- data.frame(
                      t= c(1,bp$breakpoints), 
                      t_slope= coef(bp)[,2],
                      t_slope_break=1
                      )
    y_hat=fitted.values(bp)
  })
  
  try({
    temp <- temp %>% 
            mutate(y_hat = y_hat) %>%
            left_join(cdf) %>% 
            fill(t_slope) %>%
            mutate(t_slope_percent_change = round((exp(t_slope)-1)*100,2))
    
    temp_list[[as.character(q)]] <- temp
  })
  #if( is.na( temp_list[[as.character(q)]]$y_hat) ) {print("error"); break}
}
#"13055"
temp_df <- bind_rows(temp_list)
dim(temp_df)

temp_list[["New York_New York City_NA"]]


```

```{r}
temp_df_max <- temp_df %>% group_by(fips) %>% filter(date_asdate==max(date_asdate)) %>% ungroup()


hist(temp_df_max$t_slope_percent_change, breaks=50)

temp_df_max %>% ggplot() + geom_density(aes(x=t_slope_percent_change))

```

```{r}
temp_df %>% 
  head(1000) %>%
  ggplot() +
  geom_line(aes(x=date_asdate,
                y=t_slope_percent_change,
                color=fips))  + theme(legend.position = "none")

```

```{r}
temp_df %>%
  filter(place %in% "New York_New York City_NA")  %>% 
  mutate(date_asdate_rank=rank(date_asdate)) %>%
  ggplot() +
  geom_point(aes(x=date_asdate,y=t_slope_percent_change))


temp_df %>%
  filter(place %in% "New York_New York City_NA")  %>% 
  ggplot() +
  geom_point(aes(x=date_asdate,y=confirmed_log)) +
  geom_line(aes(x=date_asdate,y=y_hat)) +
  #geom_point(aes(x=date_asdate,y=t_slope_percent_change))

temp_df %>%
  filter(place %in% "Texas_Bexar_48029")  %>% 
  ggplot() +
  geom_point(aes(x=date_asdate,y=confirmed_log)) +
  geom_line(aes(x=date_asdate,y=y_hat))

library(gghighlight)
temp_df %>%
  filter(place %in% c("New York_New York City_NA","Texas_Bexar_48029","California_San Diego_06073","Florida_St. Lucie_12111") ) %>% 
  ggplot(aes(x=date_asdate, color=place)) +
  geom_point(aes(y=confirmed_log)) +
  geom_line(aes(y=y_hat)) +
  gghighlight(#prefered_label %in% c("Washington, US","Italy","China") , #"New York, US" #, "US"
                    label_params =
                      list(
                     size = 3,
                     segment.alpha=0)
              ) +
  theme_bw()

library(gghighlight)
temp_df %>%
  filter(t_slope_percent_change>1 & confirmed>20 ) %>% 
  mutate(y_hat_exp=exp(y_hat) ) %>% 
  
  ggplot(aes(x=date_asdate, color=place)) +
  geom_point(aes(y=confirmed_log)) +
  geom_line(aes(y=y_hat)) +
  gghighlight(place %in% c("New York_New York City_NA","Texas_Bexar_48029","California_San Diego_06073","Florida_St. Lucie_12111") , 
                    label_params =
                      list(
                     size = 3,
                     segment.alpha=0)
              ) +
  theme_bw() + ylim(3,11.5)

library(scales)
library(gghighlight)
temp_df %>%
  filter(t_slope_percent_change>1 & confirmed>20 ) %>% 
  mutate(y_hat_exp=exp(y_hat) ) %>% 
  
  ggplot(aes(x=date_asdate, color=place)) +
  geom_point(aes(y=confirmed)) +
  geom_line(aes(y=y_hat_exp)) +
  gghighlight(place %in% c("New York_New York City_NA","Texas_Bexar_48029","California_San Diego_06073","Florida_St. Lucie_12111") , 
                    label_params =
                      list(
                     size = 3,
                     segment.alpha=0)
              ) +
  theme_bw() + scale_y_log10(labels = comma_format()) #+ ylim(10, 100000)


temp_df %>%
  filter(t_slope_percent_change>1 & confirmed>=20 ) %>% 
  mutate(y_hat_exp=exp(y_hat) ) %>% 
  
  ggplot(aes(x=days_since_20_confirmed, color=place)) +
  geom_point(aes(y=confirmed)) +
  geom_line(aes(y=y_hat_exp)) +
  gghighlight(place %in% c("New York_New York City_NA","Texas_Bexar_48029","California_San Diego_06073","Florida_St. Lucie_12111") , 
                    label_params =
                      list(
                     size = 3,
                     segment.alpha=0)
              ) +
  theme_bw() + scale_y_log10(labels = comma_format()) #+ ylim(10, 100000)



  
```

Ok so we put slope at days since 20 confirmed on the left hand side, and put other covariates on the rhs

```{r}

lhs_20 <- temp_df %>% 
            filter(t_slope_percent_change>1 & confirmed>=20 ) %>% 
            mutate(y_hat_exp=exp(y_hat) ) %>%
            left_join( state_codes %>% select(state=state_name, state_abbr ) )
dim(lhs_20)

dim(covidtracking)

library(USAboundaries) ; #install.packages('USAboundaries')

data(state_codes)

rhs_covidtracking <- covidtracking %>%
                     mutate(date_asdate = ymd(date)) %>% 
                     select(date_asdate, state_abbr=state, state_test_positive=positive, state_test_negative=negative) %>%
                     mutate( state_test = state_test_positive + state_test_negative) 



rhs_counties <- counties %>% select(fips=FIPS, TOT_MALE, TOT_FEMALE,
                                    doctors_per_cap=`Active Physicians per 100000 Population 2018 (AAMC)`,
                                    popdensity=`Density per square mile of land area - Population`
                                    ) %>% 
                mutate(pop=TOT_MALE+TOT_FEMALE) %>% mutate(pop_perc_male = TOT_MALE/pop)

xy_all <- lhs_20 %>% mutate(date_rank=rank(date_asdate)) %>% left_join(rhs_covidtracking)  %>% left_join(rhs_counties) 
dim(xy_all)

library(randomForestSRC); #install.packages('randomForestSRC')
rf <- rfsrc(t_slope_percent_change ~ days_since_20_confirmed + date_rank + state_test + pop + pop_perc_male +
              doctors_per_cap + popdensity,
            ntree = 200 , data=xy_all %>% as.data.frame()) #
rf #% variance explained: 19.6
vp <- vimp(rf)
plot(vp)

```


```{r}  
temp_df %>%
  filter(county %in% "Bexar") %>%
  ggplot() +
  geom_point(aes(x=date_asdate, y=confirmed_log)) +
  geom_line(aes(x=date_asdate, y=y_hat)) 
  
```

```{r}
#what should the cuttoff be?
temp_df %>% filter(confirmed<100) %>%
  ggplot() +
  geom_point(aes(x=confirmed, y=t_slope_percent_change)) 

#Where should we put the cutoff
temp_df %>% filter(confirmed<100) %>%
  ggplot(aes(x=confirmed , y=t_slope_percent_change)) +
  geom_point() +
  geom_smooth()

summary(temp_df$t_slope_percent_change[temp_df$confirmed>=10])

  
```

```{r}

temp_df_15 <- temp_df %>% filter(confirmed_max>10) %>% filter(days_since_15_confirmed>=1)

temp_df_15 %>% 
  ggplot(aes(x=days_since_15_confirmed , y=t_slope_percent_change)) +
  geom_point() +
  geom_smooth() + ylim(0,50)

```


```{r, eval=F}

library(WikidataR)


places <- all_long %>% dplyr::select(country,state) %>% distinct() %>% mutate(search=paste0(state,", ", country ))  %>% mutate(search= ifelse(is.na(state) | state=="none", country, state ) )
library(WikidataR)
wiki_searches <- list()
for(q in places$search){
  print(q)
  try({
    #wiki <- find_item("Bexas County")
    wiki <- find_item(q)
    temp <- as.data.frame(wiki[[1]])
    temp$search <- q
    wiki_searches[[q]] <- temp
  })
}
wiki_searches_df <- bind_rows(wiki_searches)
  
  
```